---
title: "Capítulo 13. Distribuciones continuas especiales"
output: html_document
---

## Uniforme

```{r}
a <- 2; b <- 8
punif(6, a, b) - punif(3, a, b)
(a+b)/2
(b-a)^2/12
```

## Exponencial

```{r}
lambda <- 0.25
pexp(6, rate=lambda, lower.tail=FALSE)
pexp(5, rate=lambda) - pexp(2, rate=lambda)
1/lambda
1/lambda^2
```

## Propiedad sin memoria

```{r}
s <- 4; t <- 3
cond <- pexp(s+t, rate=lambda, lower.tail=FALSE) / pexp(s, rate=lambda, lower.tail=FALSE)
directa <- pexp(t, rate=lambda, lower.tail=FALSE)
c(condicional=cond, directa=directa)
```

## Normal

```{r}
mu <- 100; sigma <- 15
pnorm(120, mu, sigma)
pnorm(115, mu, sigma) - pnorm(85, mu, sigma)
qnorm(0.95, mu, sigma)
```

## Regla 68-95-99.7

```{r}
sapply(1:3, function(k) pnorm(k)-pnorm(-k))
```

## Simulación

```{r}
set.seed(2026)
u <- runif(50000, 2, 8)
e <- rexp(50000, 0.25)
n <- rnorm(50000, 100, 15)

rbind(
 uniforme=c(media=mean(u), varianza=var(u)),
 exponencial=c(media=mean(e), varianza=var(e)),
 normal=c(media=mean(n), varianza=var(n))
)
```

## Gráficas

```{r}
par(mfrow=c(1,3))
curve(dunif(x,2,8), from=0, to=10, ylab='densidad', main='Uniforme')
curve(dexp(x,0.25), from=0, to=20, ylab='densidad', main='Exponencial')
curve(dnorm(x,100,15), from=50, to=150, ylab='densidad', main='Normal')
par(mfrow=c(1,1))
```
